# Name of workflow
name: Check Build

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          with:
            coverageCommand: npm run coverage
            debug: true
